-- Daily AI investment insight center for 猫狗智投.

CREATE TABLE IF NOT EXISTS ai_daily_insight_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    generated_at DATETIME NOT NULL,
    pipeline_status VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    pipeline_message VARCHAR(512) NULL,
    freshness_status VARCHAR(32) NOT NULL DEFAULT 'EMPTY',
    data_quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    recommendation_count INT NOT NULL DEFAULT 0,
    avoid_count INT NOT NULL DEFAULT 0,
    watch_count INT NOT NULL DEFAULT 0,
    item_count INT NOT NULL DEFAULT 0,
    low_sample_count INT NOT NULL DEFAULT 0,
    overall_hit_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    latest_report_at DATETIME NULL,
    latest_sample_at DATETIME NULL,
    latest_job_log_id BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_daily_insight_user_date (user_id, trade_date),
    KEY idx_daily_insight_user_generated (user_id, generated_at),
    KEY idx_daily_insight_status (user_id, pipeline_status, freshness_status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_daily_insight_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    snapshot_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    final_action VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    action_bucket VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    composite_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    system_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    ai_decision VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    ai_confidence DECIMAL(10, 4) NOT NULL DEFAULT 0,
    target_direction VARCHAR(16) NOT NULL DEFAULT 'SIDEWAYS',
    risk_level VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
    risk_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    data_quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    freshness_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    freshness_status VARCHAR(32) NOT NULL DEFAULT 'EMPTY',
    freshness_message VARCHAR(512) NULL,
    historical_hit_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    historical_sample_count INT NOT NULL DEFAULT 0,
    confidence_level VARCHAR(32) NOT NULL DEFAULT 'LOW_SAMPLE',
    trigger_factors_json MEDIUMTEXT NULL,
    reason_summary VARCHAR(512) NULL,
    report_id BIGINT NULL,
    prediction_id BIGINT NULL,
    sample_id BIGINT NULL,
    report_generated_at DATETIME NULL,
    sample_time DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_daily_insight_stock (user_id, stock_code, trade_date),
    KEY idx_daily_insight_item_snapshot_action (snapshot_id, action_bucket),
    KEY idx_daily_insight_item_score (snapshot_id, composite_score),
    KEY idx_daily_insight_item_prediction (prediction_id),
    KEY idx_daily_insight_item_report (report_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
