CREATE TABLE IF NOT EXISTS user_account (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    display_name VARCHAR(64) NULL,
    email VARCHAR(128) NULL,
    phone VARCHAR(32) NULL,
    password_hash VARCHAR(255) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    risk_preference VARCHAR(16) NULL,
    last_login_at DATETIME NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_account_username (username),
    UNIQUE KEY uk_user_account_email (email),
    UNIQUE KEY uk_user_account_phone (phone)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS watch_stock (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    market VARCHAR(16) NULL,
    group_name VARCHAR(64) NOT NULL DEFAULT '全部',
    priority INT NOT NULL DEFAULT 100,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_watch_stock_user_code (user_id, stock_code),
    KEY idx_watch_stock_group (user_id, group_name)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS trade_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    side VARCHAR(16) NOT NULL DEFAULT 'BUY',
    price DECIMAL(18, 4) NOT NULL,
    quantity INT NOT NULL,
    fee DECIMAL(18, 4) NOT NULL DEFAULT 0,
    traded_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_trade_record_user_time (user_id, traded_at),
    KEY idx_trade_record_stock (user_id, stock_code)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_model_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    api_base_url VARCHAR(512) NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    api_key VARCHAR(512) NULL,
    timeout_ms INT NOT NULL DEFAULT 60000,
    temperature DECIMAL(4, 2) NOT NULL DEFAULT 0.20,
    max_tokens INT NOT NULL DEFAULT 2048,
    intraday_interval_minutes INT NOT NULL DEFAULT 30,
    close_analysis_time VARCHAR(16) NOT NULL DEFAULT '15:30',
    analysis_scope VARCHAR(64) NOT NULL DEFAULT '全部自选股',
    prompt_template TEXT NULL,
    auto_close_pipeline_enabled TINYINT NOT NULL DEFAULT 0,
    auto_close_pipeline_last_run_at DATETIME NULL,
    auto_close_pipeline_last_finished_at DATETIME NULL,
    auto_close_pipeline_last_status VARCHAR(32) NOT NULL DEFAULT 'IDLE',
    auto_close_pipeline_last_message TEXT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_model_config_user (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_prompt_template (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ai_prompt_template_user_updated (user_id, updated_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_analysis_report (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    score INT NULL,
    advice VARCHAR(64) NULL,
    technical_analysis TEXT NULL,
    risk_warning TEXT NULL,
    buy_sell_points TEXT NULL,
    prompt_summary TEXT NULL,
    raw_prompt MEDIUMTEXT NULL,
    raw_response MEDIUMTEXT NULL,
    source_model VARCHAR(128) NULL,
    prompt_template_id BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    error_message TEXT NULL,
    report_date DATE NOT NULL,
    generated_at DATETIME NOT NULL,
    sample_id BIGINT NULL,
    prediction_id BIGINT NULL,
    strategy_version_id BIGINT NULL,
    data_quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    calibrated_confidence DECIMAL(10, 4) NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ai_report_user_time (user_id, generated_at),
    KEY idx_ai_report_stock_time (stock_code, generated_at),
    KEY idx_ai_report_sample (sample_id),
    KEY idx_ai_report_prediction (prediction_id),
    UNIQUE KEY uk_ai_report_daily_source (user_id, stock_code, report_date, source_model, deleted)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_analysis_outcome (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    report_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    report_date DATE NOT NULL,
    horizon_days INT NOT NULL,
    prediction_direction VARCHAR(16) NOT NULL,
    actual_direction VARCHAR(16) NOT NULL,
    entry_price DECIMAL(18, 4) NOT NULL DEFAULT 0,
    close_price DECIMAL(18, 4) NOT NULL DEFAULT 0,
    high_price DECIMAL(18, 4) NOT NULL DEFAULT 0,
    low_price DECIMAL(18, 4) NOT NULL DEFAULT 0,
    pct_change DECIMAL(10, 4) NOT NULL DEFAULT 0,
    max_drawdown DECIMAL(10, 4) NOT NULL DEFAULT 0,
    direction_correct TINYINT NOT NULL DEFAULT 0,
    success TINYINT NOT NULL DEFAULT 0,
    success_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    evaluated_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_outcome_report_horizon (user_id, report_id, horizon_days, deleted),
    KEY idx_ai_outcome_user_eval (user_id, evaluated_at),
    KEY idx_ai_outcome_stock_date (stock_code, report_date)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_analysis_decision (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    report_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    decision VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    confidence DECIMAL(8, 4) NOT NULL DEFAULT 0,
    holding_period VARCHAR(32) NOT NULL DEFAULT '1-3d',
    target_direction VARCHAR(16) NOT NULL DEFAULT 'SIDEWAYS',
    risk_level VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    summary VARCHAR(1024) NULL,
    factors_json MEDIUMTEXT NULL,
    raw_decision_json MEDIUMTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_decision_user_report (user_id, report_id),
    KEY idx_ai_decision_stock (user_id, stock_code),
    KEY idx_ai_decision_direction (user_id, target_direction)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_analysis_factor_hit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    report_id BIGINT NOT NULL,
    outcome_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    factor_code VARCHAR(64) NOT NULL,
    factor_name VARCHAR(128) NOT NULL,
    factor_group VARCHAR(32) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    weight_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    reason VARCHAR(512) NULL,
    success_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    pct_change DECIMAL(10, 4) NOT NULL DEFAULT 0,
    market_regime VARCHAR(32) NOT NULL DEFAULT '未知',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_factor_hit_user_factor (user_id, factor_code),
    KEY idx_factor_hit_outcome (outcome_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_factor_stat (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    factor_code VARCHAR(64) NOT NULL,
    factor_name VARCHAR(128) NOT NULL,
    factor_group VARCHAR(32) NOT NULL,
    market_regime VARCHAR(32) NOT NULL DEFAULT '未知',
    sample_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    success_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    avg_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    avg_drawdown DECIMAL(10, 4) NOT NULL DEFAULT 0,
    weight_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    last_evaluated_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_factor_stat_user_factor_regime (user_id, factor_code, market_regime),
    KEY idx_factor_stat_user_weight (user_id, weight_score)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_strategy_version (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    version_no VARCHAR(64) NOT NULL,
    title VARCHAR(128) NOT NULL,
    strategy_summary TEXT NULL,
    factor_snapshot MEDIUMTEXT NULL,
    prompt_template MEDIUMTEXT NULL,
    avg_success_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    avg_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    max_drawdown DECIMAL(10, 4) NOT NULL DEFAULT 0,
    sample_count INT NOT NULL DEFAULT 0,
    active TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_strategy_version_user_no (user_id, version_no),
    KEY idx_strategy_version_user_active (user_id, active)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_strategy_evolution_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    strategy_version_id BIGINT NULL,
    action_type VARCHAR(32) NOT NULL,
    action_summary VARCHAR(512) NULL,
    before_snapshot MEDIUMTEXT NULL,
    after_snapshot MEDIUMTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_strategy_log_user_time (user_id, created_at),
    KEY idx_strategy_log_version (strategy_version_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_chat_session (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    model_name VARCHAR(128) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ai_chat_session_user_updated (user_id, updated_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_chat_message (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    session_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    message_role VARCHAR(16) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    model_name VARCHAR(128) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS',
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_ai_chat_message_session_time (session_id, created_at),
    KEY idx_ai_chat_message_user_time (user_id, created_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_user_memory (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    memory_summary TEXT NULL,
    last_interaction_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_user_memory_user (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS news_flash (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(512) NOT NULL,
    source VARCHAR(64) NULL,
    url VARCHAR(1024) NULL,
    published_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_news_flash_published (published_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS market_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR(32) NOT NULL,
    name VARCHAR(64) NULL,
    market VARCHAR(16) NULL,
    latest_price DECIMAL(18, 4) NOT NULL,
    change_amount DECIMAL(18, 4) NOT NULL DEFAULT 0,
    change_percent DECIMAL(10, 4) NOT NULL DEFAULT 0,
    volume_ratio DECIMAL(10, 4) NULL,
    amount DECIMAL(24, 4) NULL,
    quote_time DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_market_snapshot_symbol_time (symbol, quote_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS stock_kline (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    stock_code VARCHAR(16) NOT NULL,
    period VARCHAR(16) NOT NULL DEFAULT 'day',
    trade_date DATE NOT NULL,
    open_price DECIMAL(18, 4) NOT NULL,
    close_price DECIMAL(18, 4) NOT NULL,
    low_price DECIMAL(18, 4) NOT NULL,
    high_price DECIMAL(18, 4) NOT NULL,
    volume BIGINT NULL,
    amount DECIMAL(24, 4) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_stock_kline_code_period_date (stock_code, period, trade_date)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_stock_universe (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    universe_code VARCHAR(64) NOT NULL,
    universe_name VARCHAR(128) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    filters_json MEDIUMTEXT NULL,
    active TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_universe_user_code (user_id, universe_code),
    KEY idx_ai_universe_user_active (user_id, active)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_prediction_sample (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    sample_time DATETIME NOT NULL,
    trade_date DATE NOT NULL,
    sample_phase VARCHAR(32) NOT NULL,
    universe_code VARCHAR(64) NOT NULL DEFAULT 'WATCHLIST',
    market_regime VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    sector_code VARCHAR(32) NULL,
    sector_name VARCHAR(64) NULL,
    data_quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    tradable TINYINT NOT NULL DEFAULT 1,
    exclude_reason VARCHAR(255) NULL,
    feature_snapshot MEDIUMTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ai_sample_user_stock_phase (user_id, stock_code, trade_date, sample_phase, universe_code),
    KEY idx_ai_sample_user_time (user_id, sample_time),
    KEY idx_ai_sample_stock_date (stock_code, trade_date),
    KEY idx_ai_sample_regime (user_id, market_regime)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_factor_definition (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    factor_code VARCHAR(64) NOT NULL,
    factor_name VARCHAR(128) NOT NULL,
    factor_group VARCHAR(32) NOT NULL,
    direction VARCHAR(16) NOT NULL DEFAULT 'NEUTRAL',
    formula_desc TEXT NULL,
    required_fields_json MEDIUMTEXT NULL,
    default_weight DECIMAL(10, 4) NOT NULL DEFAULT 0,
    enabled TINYINT NOT NULL DEFAULT 1,
    version_no VARCHAR(32) NOT NULL DEFAULT 'v1',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_factor_definition_code_version (factor_code, version_no),
    KEY idx_factor_definition_group (factor_group, enabled)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_factor_value (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    factor_code VARCHAR(64) NOT NULL,
    factor_value DECIMAL(18, 6) NULL,
    normalized_value DECIMAL(18, 6) NULL,
    hit TINYINT NOT NULL DEFAULT 0,
    direction VARCHAR(16) NOT NULL DEFAULT 'NEUTRAL',
    evidence VARCHAR(512) NULL,
    calculated_at DATETIME NOT NULL,
    UNIQUE KEY uk_factor_value_sample_factor (sample_id, factor_code),
    KEY idx_factor_value_sample (sample_id),
    KEY idx_factor_value_user_factor (user_id, factor_code)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_prediction_result (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    report_id BIGINT NULL,
    strategy_version_id BIGINT NOT NULL DEFAULT 0,
    model_version_id BIGINT NOT NULL DEFAULT 0,
    prompt_template_id BIGINT NOT NULL DEFAULT 0,
    action VARCHAR(16) NOT NULL,
    target_direction VARCHAR(16) NOT NULL,
    horizon_days INT NOT NULL DEFAULT 3,
    confidence DECIMAL(10, 4) NOT NULL DEFAULT 0,
    score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    rank_no INT NULL,
    risk_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    reason_json MEDIUMTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_prediction_user_sample_strategy (user_id, sample_id, strategy_version_id, horizon_days),
    KEY idx_prediction_user_sample (user_id, sample_id),
    KEY idx_prediction_strategy_time (strategy_version_id, created_at),
    KEY idx_prediction_rank (user_id, horizon_days, rank_no)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_prediction_label (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    prediction_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    horizon_days INT NOT NULL,
    entry_price DECIMAL(18, 4) NOT NULL DEFAULT 0,
    exit_price DECIMAL(18, 4) NOT NULL DEFAULT 0,
    close_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    max_favorable_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    max_adverse_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    benchmark_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    sector_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    excess_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    net_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    hit_direction TINYINT NOT NULL DEFAULT 0,
    hit_target TINYINT NOT NULL DEFAULT 0,
    hit_stop_loss TINYINT NOT NULL DEFAULT 0,
    tradable TINYINT NOT NULL DEFAULT 1,
    label_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    label_status VARCHAR(32) NOT NULL DEFAULT 'READY',
    evaluated_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_prediction_label_horizon (user_id, prediction_id, horizon_days),
    KEY idx_prediction_label_stock (stock_code, evaluated_at),
    KEY idx_prediction_label_sample (sample_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_strategy_experiment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    universe_code VARCHAR(64) NOT NULL DEFAULT 'WATCHLIST',
    train_start_date DATE NULL,
    train_end_date DATE NULL,
    validation_start_date DATE NULL,
    validation_end_date DATE NULL,
    test_start_date DATE NULL,
    test_end_date DATE NULL,
    config_json MEDIUMTEXT NULL,
    metrics_json MEDIUMTEXT NULL,
    baseline_metrics_json MEDIUMTEXT NULL,
    can_promote TINYINT NOT NULL DEFAULT 0,
    promoted_strategy_version_id BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_ai_experiment_user_time (user_id, created_at),
    KEY idx_ai_experiment_status (user_id, status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_backtest_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    strategy_version_id BIGINT NOT NULL DEFAULT 0,
    experiment_id BIGINT NULL,
    title VARCHAR(128) NOT NULL,
    universe_code VARCHAR(64) NOT NULL DEFAULT 'WATCHLIST',
    horizon_days INT NOT NULL DEFAULT 3,
    top_k INT NOT NULL DEFAULT 5,
    start_date DATE NULL,
    end_date DATE NULL,
    total_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    win_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    avg_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    max_drawdown DECIMAL(10, 4) NOT NULL DEFAULT 0,
    benchmark_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    trade_count INT NOT NULL DEFAULT 0,
    metrics_json MEDIUMTEXT NULL,
    equity_curve_json MEDIUMTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_backtest_user_time (user_id, created_at),
    KEY idx_backtest_strategy (strategy_version_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_backtest_trade (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    backtest_run_id BIGINT NOT NULL,
    prediction_id BIGINT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    entry_date DATE NOT NULL,
    exit_date DATE NOT NULL,
    entry_price DECIMAL(18, 4) NOT NULL DEFAULT 0,
    exit_price DECIMAL(18, 4) NOT NULL DEFAULT 0,
    net_return DECIMAL(10, 4) NOT NULL DEFAULT 0,
    max_drawdown DECIMAL(10, 4) NOT NULL DEFAULT 0,
    rank_no INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_backtest_trade_run (backtest_run_id),
    KEY idx_backtest_trade_stock (stock_code, entry_date)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_learning_job_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL DEFAULT 0,
    job_name VARCHAR(128) NOT NULL,
    job_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at DATETIME NOT NULL,
    finished_at DATETIME NULL,
    processed_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_learning_job_time (job_type, started_at),
    KEY idx_learning_job_user (user_id, started_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_model_eval_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    model_name VARCHAR(128) NOT NULL,
    provider VARCHAR(64) NOT NULL DEFAULT 'openai-compatible',
    prompt_template_id BIGINT NOT NULL DEFAULT 0,
    eval_type VARCHAR(64) NOT NULL DEFAULT 'REPORT_JSON',
    json_success_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    avg_latency_ms DECIMAL(18, 4) NOT NULL DEFAULT 0,
    sample_count INT NOT NULL DEFAULT 0,
    score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    metrics_json MEDIUMTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'READY',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_model_eval_user_time (user_id, created_at),
    KEY idx_model_eval_model (model_name, created_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_daily_insight_snapshot (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    generated_at DATETIME NOT NULL,
    pipeline_status VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
    pipeline_message VARCHAR(512) NULL,
    freshness_status VARCHAR(32) NOT NULL DEFAULT 'EMPTY',
    data_quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    recommendation_count INT NOT NULL DEFAULT 0,
    avoid_count INT NOT NULL DEFAULT 0,
    watch_count INT NOT NULL DEFAULT 0,
    item_count INT NOT NULL DEFAULT 0,
    low_sample_count INT NOT NULL DEFAULT 0,
    overall_hit_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    latest_report_at DATETIME NULL,
    latest_sample_at DATETIME NULL,
    latest_job_log_id BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_daily_insight_user_date (user_id, trade_date),
    KEY idx_daily_insight_user_generated (user_id, generated_at),
    KEY idx_daily_insight_status (user_id, pipeline_status, freshness_status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_daily_insight_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    snapshot_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    final_action VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    action_bucket VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    composite_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    system_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    ai_decision VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    ai_confidence DECIMAL(10, 4) NOT NULL DEFAULT 0,
    target_direction VARCHAR(16) NOT NULL DEFAULT 'SIDEWAYS',
    risk_level VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
    risk_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    data_quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    freshness_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    freshness_status VARCHAR(32) NOT NULL DEFAULT 'EMPTY',
    freshness_message VARCHAR(512) NULL,
    historical_hit_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    historical_sample_count INT NOT NULL DEFAULT 0,
    confidence_level VARCHAR(32) NOT NULL DEFAULT 'LOW_SAMPLE',
    trigger_factors_json MEDIUMTEXT NULL,
    reason_summary VARCHAR(512) NULL,
    report_id BIGINT NULL,
    prediction_id BIGINT NULL,
    sample_id BIGINT NULL,
    report_generated_at DATETIME NULL,
    sample_time DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_daily_insight_stock (user_id, stock_code, trade_date),
    KEY idx_daily_insight_item_snapshot_action (snapshot_id, action_bucket),
    KEY idx_daily_insight_item_score (snapshot_id, composite_score),
    KEY idx_daily_insight_item_prediction (prediction_id),
    KEY idx_daily_insight_item_report (report_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

INSERT IGNORE INTO user_account (id, username, display_name, email, status)
VALUES (1, 'demo', '默认用户', NULL, 'ACTIVE');

-- 猫狗智投 AI evolution V2.
-- V1 tables remain readable. V2 tables are isolated so legacy statistics cannot
-- overwrite point-in-time samples, predictions, labels, or release evidence.

CREATE TABLE IF NOT EXISTS ai_data_batch (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    sample_phase VARCHAR(32) NOT NULL,
    as_of_time DATETIME(3) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    source_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    quote_as_of DATETIME(3) NULL,
    kline_as_of DATE NULL,
    finance_as_of DATE NULL,
    sector_as_of DATETIME(3) NULL,
    news_as_of DATETIME(3) NULL,
    quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    quality_status VARCHAR(32) NOT NULL DEFAULT 'UNAVAILABLE',
    item_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    started_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_data_batch_idempotency (user_id, idempotency_key),
    KEY idx_ai_data_batch_trade_phase (trade_date, sample_phase, status),
    KEY idx_ai_data_batch_user_time (user_id, as_of_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_sample_v2 (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    data_batch_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    stock_name VARCHAR(64) NULL,
    trade_date DATE NOT NULL,
    sample_phase VARCHAR(32) NOT NULL,
    as_of_time DATETIME(3) NOT NULL,
    universe_code VARCHAR(64) NOT NULL,
    universe_version VARCHAR(64) NOT NULL,
    market_regime VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    sector_code VARCHAR(32) NULL,
    sector_name VARCHAR(64) NULL,
    data_quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    quality_status VARCHAR(32) NOT NULL DEFAULT 'UNAVAILABLE',
    tradable_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    exclude_reason VARCHAR(255) NULL,
    feature_version VARCHAR(64) NOT NULL,
    feature_snapshot MEDIUMTEXT NOT NULL,
    source_fingerprint VARCHAR(128) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_sample_v2_snapshot (user_id, stock_code, as_of_time, sample_phase, universe_version),
    KEY idx_ai_sample_v2_batch (data_batch_id),
    KEY idx_ai_sample_v2_user_trade (user_id, trade_date, universe_code),
    KEY idx_ai_sample_v2_stock_time (stock_code, as_of_time),
    KEY idx_ai_sample_v2_quality (user_id, quality_status, tradable_status),
    CONSTRAINT fk_ai_sample_v2_batch FOREIGN KEY (data_batch_id) REFERENCES ai_data_batch (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_factor_value_v2 (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    factor_code VARCHAR(64) NOT NULL,
    factor_version VARCHAR(32) NOT NULL,
    factor_group VARCHAR(32) NOT NULL,
    direction VARCHAR(16) NOT NULL DEFAULT 'NEUTRAL',
    raw_value DECIMAL(24, 8) NULL,
    normalized_value DECIMAL(18, 8) NULL,
    hit TINYINT NOT NULL DEFAULT 0,
    missing TINYINT NOT NULL DEFAULT 0,
    missing_reason VARCHAR(255) NULL,
    evidence VARCHAR(512) NULL,
    input_fingerprint VARCHAR(128) NOT NULL,
    calculated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_factor_v2_sample_code (sample_id, factor_code, factor_version),
    KEY idx_ai_factor_v2_user_code (user_id, factor_code, factor_version),
    KEY idx_ai_factor_v2_stock_time (stock_code, calculated_at),
    CONSTRAINT fk_ai_factor_value_v2_sample FOREIGN KEY (sample_id) REFERENCES ai_sample_v2 (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_trading_calendar (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    market_code VARCHAR(16) NOT NULL,
    trade_date DATE NOT NULL,
    calendar_version VARCHAR(64) NOT NULL,
    is_trade_day TINYINT NOT NULL,
    session_open_time TIME NULL,
    session_close_time TIME NULL,
    previous_trade_date DATE NULL,
    next_trade_date DATE NULL,
    source_name VARCHAR(64) NOT NULL,
    source_as_of DATETIME(3) NOT NULL,
    source_fingerprint VARCHAR(128) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_trading_calendar_version (market_code, trade_date, calendar_version),
    KEY idx_ai_trading_calendar_lookup (market_code, calendar_version, is_trade_day, trade_date),
    KEY idx_ai_trading_calendar_source (source_fingerprint)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_training_dataset (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    dataset_key VARCHAR(96) NOT NULL,
    version_no VARCHAR(64) NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    feature_version VARCHAR(64) NOT NULL,
    label_version VARCHAR(32) NOT NULL,
    calendar_version VARCHAR(64) NOT NULL,
    as_of_time DATETIME(3) NOT NULL,
    train_start_date DATE NOT NULL,
    train_end_date DATE NOT NULL,
    validation_start_date DATE NOT NULL,
    validation_end_date DATE NOT NULL,
    test_start_date DATE NOT NULL,
    test_end_date DATE NOT NULL,
    max_horizon_days INT NOT NULL,
    source_query_json MEDIUMTEXT NOT NULL,
    selection_policy_json MEDIUMTEXT NOT NULL,
    lineage_fingerprint VARCHAR(128) NOT NULL,
    artifact_uri VARCHAR(512) NULL,
    artifact_checksum VARCHAR(128) NULL,
    row_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'BUILDING',
    finalized_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_training_dataset_version (user_id, dataset_key, version_no),
    UNIQUE KEY uk_ai_training_dataset_lineage (user_id, lineage_fingerprint),
    KEY idx_ai_training_dataset_status (user_id, status, as_of_time),
    CONSTRAINT chk_ai_training_dataset_dates CHECK (train_start_date <= train_end_date AND train_end_date < validation_start_date AND validation_start_date <= validation_end_date AND validation_end_date < test_start_date AND test_start_date <= test_end_date)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_model_version (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    training_dataset_id BIGINT NOT NULL,
    model_key VARCHAR(64) NOT NULL,
    version_no VARCHAR(64) NOT NULL,
    model_type VARCHAR(32) NOT NULL,
    algorithm VARCHAR(64) NOT NULL,
    feature_version VARCHAR(64) NOT NULL,
    trainer_version VARCHAR(64) NOT NULL,
    random_seed BIGINT NOT NULL,
    artifact_uri VARCHAR(512) NULL,
    artifact_checksum VARCHAR(128) NULL,
    feature_manifest_uri VARCHAR(512) NULL,
    feature_manifest_checksum VARCHAR(128) NULL,
    train_start_date DATE NULL,
    train_end_date DATE NULL,
    validation_start_date DATE NULL,
    validation_end_date DATE NULL,
    test_start_date DATE NULL,
    test_end_date DATE NULL,
    parameters_json MEDIUMTEXT NULL,
    metrics_json MEDIUMTEXT NULL,
    calibration_json MEDIUMTEXT NULL,
    sample_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'CANDIDATE',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_model_version_key_no (user_id, model_key, version_no),
    KEY idx_ai_model_version_status (user_id, status, created_at),
    KEY idx_ai_model_version_dataset (training_dataset_id, created_at),
    CONSTRAINT fk_ai_model_version_dataset FOREIGN KEY (training_dataset_id) REFERENCES ai_training_dataset (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_strategy_release (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    version_no VARCHAR(64) NOT NULL,
    title VARCHAR(128) NOT NULL,
    model_version_id BIGINT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    release_role VARCHAR(32) NOT NULL DEFAULT 'CHALLENGER',
    active_champion_guard TINYINT GENERATED ALWAYS AS (CASE WHEN release_role = 'CHAMPION' AND status = 'ACTIVE' THEN 1 ELSE NULL END) STORED,
    config_json MEDIUMTEXT NOT NULL,
    factor_snapshot_json MEDIUMTEXT NULL,
    validation_metrics_json MEDIUMTEXT NULL,
    promotion_reason TEXT NULL,
    rollback_reason TEXT NULL,
    shadow_started_at DATETIME(3) NULL,
    shadow_ended_at DATETIME(3) NULL,
    activated_at DATETIME(3) NULL,
    retired_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_strategy_release_user_no (user_id, version_no),
    UNIQUE KEY uk_ai_strategy_release_active_champion (user_id, active_champion_guard),
    KEY idx_ai_strategy_release_role (user_id, release_role, status),
    KEY idx_ai_strategy_release_model (model_version_id),
    CONSTRAINT fk_ai_strategy_release_model FOREIGN KEY (model_version_id) REFERENCES ai_model_version (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_prediction_v2 (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    strategy_release_id BIGINT NOT NULL,
    model_version_id BIGINT NULL,
    stock_code VARCHAR(16) NOT NULL,
    trade_date DATE NOT NULL,
    sample_phase VARCHAR(32) NOT NULL,
    inference_mode VARCHAR(32) NOT NULL,
    input_fingerprint VARCHAR(128) NOT NULL,
    horizon_days INT NOT NULL,
    expected_return DECIMAL(12, 6) NOT NULL DEFAULT 0,
    expected_excess_return DECIMAL(12, 6) NOT NULL DEFAULT 0,
    probability_up DECIMAL(10, 6) NOT NULL DEFAULT 0,
    probability_down DECIMAL(10, 6) NOT NULL DEFAULT 0,
    calibrated_confidence DECIMAL(10, 4) NOT NULL DEFAULT 0,
    score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    risk_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    rank_no INT NULL,
    action VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    action_bucket VARCHAR(16) NOT NULL DEFAULT 'WATCH',
    target_direction VARCHAR(16) NOT NULL DEFAULT 'SIDEWAYS',
    abstain_reason VARCHAR(255) NULL,
    reason_json MEDIUMTEXT NULL,
    idempotency_key VARCHAR(192) NOT NULL,
    predicted_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_prediction_v2_idempotency (user_id, idempotency_key),
    UNIQUE KEY uk_ai_prediction_v2_business (user_id, stock_code, trade_date, sample_phase, horizon_days, strategy_release_id, inference_mode, input_fingerprint),
    KEY idx_ai_prediction_v2_sample (sample_id, horizon_days),
    KEY idx_ai_prediction_v2_trade_rank (user_id, trade_date, sample_phase, inference_mode, action_bucket, rank_no),
    KEY idx_ai_prediction_v2_release (strategy_release_id, trade_date, horizon_days),
    KEY idx_ai_prediction_v2_model (model_version_id, trade_date),
    CONSTRAINT fk_ai_prediction_v2_sample FOREIGN KEY (sample_id) REFERENCES ai_sample_v2 (id),
    CONSTRAINT fk_ai_prediction_v2_release FOREIGN KEY (strategy_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_prediction_v2_model FOREIGN KEY (model_version_id) REFERENCES ai_model_version (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_label_v2 (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    prediction_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    entry_calendar_id BIGINT NULL,
    exit_calendar_id BIGINT NULL,
    stock_code VARCHAR(16) NOT NULL,
    horizon_days INT NOT NULL,
    label_version VARCHAR(32) NOT NULL,
    calendar_version VARCHAR(64) NOT NULL,
    input_fingerprint VARCHAR(128) NOT NULL,
    entry_trade_date DATE NULL,
    exit_trade_date DATE NULL,
    entry_price DECIMAL(18, 4) NULL,
    exit_price DECIMAL(18, 4) NULL,
    gross_return DECIMAL(12, 6) NULL,
    net_return DECIMAL(12, 6) NULL,
    benchmark_return DECIMAL(12, 6) NULL,
    sector_return DECIMAL(12, 6) NULL,
    excess_return DECIMAL(12, 6) NULL,
    max_favorable_return DECIMAL(12, 6) NULL,
    max_adverse_return DECIMAL(12, 6) NULL,
    execution_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    execution_reason VARCHAR(255) NULL,
    action_evaluation VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    hit_direction TINYINT NULL,
    hit_target TINYINT NULL,
    hit_stop_loss TINYINT NULL,
    label_score DECIMAL(10, 4) NULL,
    label_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    matured_at DATETIME(3) NULL,
    verified_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_label_v2_version (user_id, prediction_id, horizon_days, label_version),
    KEY idx_ai_label_v2_pending (user_id, label_status, horizon_days),
    KEY idx_ai_label_v2_stock_exit (stock_code, exit_trade_date),
    KEY idx_ai_label_v2_sample (sample_id),
    KEY idx_ai_label_v2_calendar (entry_calendar_id, exit_calendar_id),
    CONSTRAINT fk_ai_label_v2_prediction FOREIGN KEY (prediction_id) REFERENCES ai_prediction_v2 (id),
    CONSTRAINT fk_ai_label_v2_sample FOREIGN KEY (sample_id) REFERENCES ai_sample_v2 (id),
    CONSTRAINT fk_ai_label_v2_entry_calendar FOREIGN KEY (entry_calendar_id) REFERENCES ai_trading_calendar (id),
    CONSTRAINT fk_ai_label_v2_exit_calendar FOREIGN KEY (exit_calendar_id) REFERENCES ai_trading_calendar (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_label_cost_evidence (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    label_id BIGINT NOT NULL,
    cost_model_version VARCHAR(64) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    quantity DECIMAL(20, 4) NOT NULL,
    entry_notional DECIMAL(20, 6) NOT NULL,
    exit_notional DECIMAL(20, 6) NOT NULL,
    buy_commission_rate DECIMAL(12, 8) NOT NULL,
    sell_commission_rate DECIMAL(12, 8) NOT NULL,
    stamp_duty_rate DECIMAL(12, 8) NOT NULL,
    transfer_fee_rate DECIMAL(12, 8) NOT NULL,
    slippage_bps DECIMAL(12, 4) NOT NULL,
    buy_commission_amount DECIMAL(20, 6) NOT NULL,
    sell_commission_amount DECIMAL(20, 6) NOT NULL,
    stamp_duty_amount DECIMAL(20, 6) NOT NULL,
    transfer_fee_amount DECIMAL(20, 6) NOT NULL,
    slippage_amount DECIMAL(20, 6) NOT NULL,
    total_cost_amount DECIMAL(20, 6) NOT NULL,
    evidence_json MEDIUMTEXT NOT NULL,
    source_fingerprint VARCHAR(128) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_label_cost_evidence_version (label_id, cost_model_version),
    KEY idx_ai_label_cost_evidence_source (source_fingerprint),
    CONSTRAINT fk_ai_label_cost_evidence_label FOREIGN KEY (label_id) REFERENCES ai_label_v2 (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_training_dataset_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    training_dataset_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    split_type VARCHAR(16) NOT NULL,
    sequence_no INT NOT NULL,
    sample_as_of_time DATETIME(3) NOT NULL,
    label_available_at DATETIME(3) NOT NULL,
    feature_fingerprint VARCHAR(128) NOT NULL,
    label_fingerprint VARCHAR(128) NOT NULL,
    included_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_training_dataset_item_lineage (training_dataset_id, sample_id, label_id),
    UNIQUE KEY uk_ai_training_dataset_item_sequence (training_dataset_id, split_type, sequence_no),
    KEY idx_ai_training_dataset_item_split (training_dataset_id, split_type, sample_as_of_time),
    KEY idx_ai_training_dataset_item_label (label_id),
    CONSTRAINT fk_ai_training_dataset_item_dataset FOREIGN KEY (training_dataset_id) REFERENCES ai_training_dataset (id),
    CONSTRAINT fk_ai_training_dataset_item_sample FOREIGN KEY (sample_id) REFERENCES ai_sample_v2 (id),
    CONSTRAINT fk_ai_training_dataset_item_label FOREIGN KEY (label_id) REFERENCES ai_label_v2 (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_factor_performance_v2 (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    factor_code VARCHAR(64) NOT NULL,
    factor_version VARCHAR(32) NOT NULL,
    horizon_days INT NOT NULL,
    market_regime VARCHAR(32) NOT NULL,
    window_type VARCHAR(32) NOT NULL,
    window_start_date DATE NOT NULL,
    window_end_date DATE NOT NULL,
    input_fingerprint VARCHAR(128) NOT NULL,
    sample_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    success_rate DECIMAL(10, 4) NOT NULL DEFAULT 0,
    wilson_lower_bound DECIMAL(10, 4) NOT NULL DEFAULT 0,
    rank_ic DECIMAL(12, 6) NULL,
    avg_excess_return DECIMAL(12, 6) NULL,
    avg_adverse_return DECIMAL(12, 6) NULL,
    stability_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    psi_score DECIMAL(10, 6) NULL,
    confidence_level VARCHAR(32) NOT NULL DEFAULT 'LOW_SAMPLE',
    drift_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    evaluated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_factor_perf_v2_window (user_id, factor_code, factor_version, horizon_days, market_regime, window_type, window_start_date, window_end_date),
    KEY idx_ai_factor_perf_v2_rank (user_id, horizon_days, confidence_level, wilson_lower_bound),
    KEY idx_ai_factor_perf_v2_window (user_id, factor_code, factor_version, window_start_date, window_end_date),
    CONSTRAINT chk_ai_factor_perf_v2_window CHECK (window_start_date <= window_end_date)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_walk_forward_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    training_dataset_id BIGINT NOT NULL,
    strategy_release_id BIGINT NULL,
    model_version_id BIGINT NULL,
    run_key VARCHAR(160) NOT NULL,
    run_version VARCHAR(64) NOT NULL,
    objective VARCHAR(64) NOT NULL,
    horizon_days INT NOT NULL,
    purge_days INT NOT NULL,
    embargo_days INT NOT NULL,
    fold_count INT NOT NULL,
    random_seed BIGINT NOT NULL,
    input_fingerprint VARCHAR(128) NOT NULL,
    config_json MEDIUMTEXT NOT NULL,
    aggregate_metrics_json MEDIUMTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_walk_forward_run_key (user_id, run_key),
    KEY idx_ai_walk_forward_run_status (user_id, status, created_at),
    KEY idx_ai_walk_forward_run_dataset (training_dataset_id, created_at),
    KEY idx_ai_walk_forward_run_release (strategy_release_id, created_at),
    CONSTRAINT fk_ai_walk_forward_run_dataset FOREIGN KEY (training_dataset_id) REFERENCES ai_training_dataset (id),
    CONSTRAINT fk_ai_walk_forward_run_release FOREIGN KEY (strategy_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_walk_forward_run_model FOREIGN KEY (model_version_id) REFERENCES ai_model_version (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_walk_forward_fold (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    walk_forward_run_id BIGINT NOT NULL,
    fold_no INT NOT NULL,
    train_start_date DATE NOT NULL,
    train_end_date DATE NOT NULL,
    validation_start_date DATE NOT NULL,
    validation_end_date DATE NOT NULL,
    test_start_date DATE NOT NULL,
    test_end_date DATE NOT NULL,
    purge_days INT NOT NULL,
    embargo_days INT NOT NULL,
    train_sample_count INT NOT NULL DEFAULT 0,
    validation_sample_count INT NOT NULL DEFAULT 0,
    test_sample_count INT NOT NULL DEFAULT 0,
    metrics_json MEDIUMTEXT NULL,
    confidence_interval_json MEDIUMTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_walk_forward_fold_no (walk_forward_run_id, fold_no),
    KEY idx_ai_walk_forward_fold_test (walk_forward_run_id, test_start_date, test_end_date, status),
    CONSTRAINT chk_ai_walk_forward_fold_dates CHECK (train_start_date <= train_end_date AND train_end_date < validation_start_date AND validation_start_date <= validation_end_date AND validation_end_date < test_start_date AND test_start_date <= test_end_date),
    CONSTRAINT fk_ai_walk_forward_fold_run FOREIGN KEY (walk_forward_run_id) REFERENCES ai_walk_forward_run (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_walk_forward_baseline (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    walk_forward_fold_id BIGINT NOT NULL,
    strategy_release_id BIGINT NULL,
    baseline_key VARCHAR(96) NOT NULL,
    baseline_type VARCHAR(32) NOT NULL,
    benchmark_code VARCHAR(32) NULL,
    metrics_json MEDIUMTEXT NOT NULL,
    nav_json MEDIUMTEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_walk_forward_baseline_key (walk_forward_fold_id, baseline_key),
    KEY idx_ai_walk_forward_baseline_type (walk_forward_fold_id, baseline_type),
    CONSTRAINT fk_ai_walk_forward_baseline_fold FOREIGN KEY (walk_forward_fold_id) REFERENCES ai_walk_forward_fold (id),
    CONSTRAINT fk_ai_walk_forward_baseline_release FOREIGN KEY (strategy_release_id) REFERENCES ai_strategy_release (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_portfolio_backtest_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    training_dataset_id BIGINT NOT NULL,
    walk_forward_run_id BIGINT NULL,
    strategy_release_id BIGINT NOT NULL,
    model_version_id BIGINT NULL,
    run_key VARCHAR(160) NOT NULL,
    engine_version VARCHAR(64) NOT NULL,
    config_fingerprint VARCHAR(128) NOT NULL,
    input_fingerprint VARCHAR(128) NOT NULL,
    random_seed BIGINT NOT NULL,
    start_trade_date DATE NOT NULL,
    end_trade_date DATE NOT NULL,
    horizon_days INT NOT NULL,
    top_k INT NOT NULL,
    rebalance_frequency VARCHAR(32) NOT NULL,
    initial_capital DECIMAL(20, 6) NOT NULL,
    final_nav DECIMAL(20, 8) NULL,
    benchmark_final_nav DECIMAL(20, 8) NULL,
    total_return DECIMAL(12, 6) NULL,
    benchmark_return DECIMAL(12, 6) NULL,
    alpha DECIMAL(12, 6) NULL,
    annualized_return DECIMAL(12, 6) NULL,
    sharpe_ratio DECIMAL(12, 6) NULL,
    calmar_ratio DECIMAL(12, 6) NULL,
    max_drawdown DECIMAL(12, 6) NULL,
    turnover_rate DECIMAL(12, 6) NULL,
    trade_count INT NOT NULL DEFAULT 0,
    metrics_json MEDIUMTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_portfolio_backtest_run_key (user_id, run_key),
    KEY idx_ai_portfolio_backtest_release (strategy_release_id, start_trade_date, end_trade_date, status),
    KEY idx_ai_portfolio_backtest_dataset (training_dataset_id, created_at),
    KEY idx_ai_portfolio_backtest_status (user_id, status, created_at),
    CONSTRAINT chk_ai_portfolio_backtest_dates CHECK (start_trade_date <= end_trade_date),
    CONSTRAINT fk_ai_portfolio_backtest_dataset FOREIGN KEY (training_dataset_id) REFERENCES ai_training_dataset (id),
    CONSTRAINT fk_ai_portfolio_backtest_walk_run FOREIGN KEY (walk_forward_run_id) REFERENCES ai_walk_forward_run (id),
    CONSTRAINT fk_ai_portfolio_backtest_release FOREIGN KEY (strategy_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_portfolio_backtest_model FOREIGN KEY (model_version_id) REFERENCES ai_model_version (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_portfolio_backtest_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    backtest_run_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    cash_balance DECIMAL(20, 6) NOT NULL,
    market_value DECIMAL(20, 6) NOT NULL,
    total_equity DECIMAL(20, 6) NOT NULL,
    nav DECIMAL(20, 8) NOT NULL,
    benchmark_nav DECIMAL(20, 8) NOT NULL,
    daily_return DECIMAL(12, 6) NOT NULL,
    benchmark_return DECIMAL(12, 6) NOT NULL,
    drawdown DECIMAL(12, 6) NOT NULL,
    turnover_rate DECIMAL(12, 6) NOT NULL,
    gross_exposure DECIMAL(12, 6) NOT NULL,
    net_exposure DECIMAL(12, 6) NOT NULL,
    holding_count INT NOT NULL,
    transaction_cost DECIMAL(20, 6) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_portfolio_backtest_daily_date (backtest_run_id, trade_date),
    KEY idx_ai_portfolio_backtest_daily_nav (backtest_run_id, trade_date, nav),
    CONSTRAINT fk_ai_portfolio_backtest_daily_run FOREIGN KEY (backtest_run_id) REFERENCES ai_portfolio_backtest_run (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_portfolio_backtest_trade (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    backtest_run_id BIGINT NOT NULL,
    prediction_id BIGINT NULL,
    trade_key VARCHAR(128) NOT NULL,
    trade_date DATE NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    side VARCHAR(16) NOT NULL,
    order_quantity DECIMAL(20, 4) NOT NULL,
    filled_quantity DECIMAL(20, 4) NOT NULL,
    execution_price DECIMAL(18, 4) NULL,
    gross_amount DECIMAL(20, 6) NULL,
    commission_amount DECIMAL(20, 6) NOT NULL DEFAULT 0,
    stamp_duty_amount DECIMAL(20, 6) NOT NULL DEFAULT 0,
    transfer_fee_amount DECIMAL(20, 6) NOT NULL DEFAULT 0,
    slippage_amount DECIMAL(20, 6) NOT NULL DEFAULT 0,
    total_cost_amount DECIMAL(20, 6) NOT NULL DEFAULT 0,
    execution_status VARCHAR(32) NOT NULL,
    rejection_reason VARCHAR(255) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_portfolio_backtest_trade_key (backtest_run_id, trade_key),
    KEY idx_ai_portfolio_backtest_trade_stock (backtest_run_id, stock_code, trade_date),
    KEY idx_ai_portfolio_backtest_trade_prediction (prediction_id),
    CONSTRAINT fk_ai_portfolio_backtest_trade_run FOREIGN KEY (backtest_run_id) REFERENCES ai_portfolio_backtest_run (id),
    CONSTRAINT fk_ai_portfolio_backtest_trade_prediction FOREIGN KEY (prediction_id) REFERENCES ai_prediction_v2 (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_portfolio_backtest_position (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    backtest_run_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    stock_code VARCHAR(16) NOT NULL,
    quantity DECIMAL(20, 4) NOT NULL,
    average_cost DECIMAL(18, 4) NOT NULL,
    close_price DECIMAL(18, 4) NOT NULL,
    market_value DECIMAL(20, 6) NOT NULL,
    weight DECIMAL(12, 6) NOT NULL,
    unrealized_pnl DECIMAL(20, 6) NOT NULL,
    daily_pnl DECIMAL(20, 6) NOT NULL,
    return_contribution DECIMAL(12, 6) NOT NULL,
    tradable_status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_portfolio_backtest_position_stock (backtest_run_id, trade_date, stock_code),
    KEY idx_ai_portfolio_backtest_position_weight (backtest_run_id, trade_date, weight),
    KEY idx_ai_portfolio_backtest_position_stock (stock_code, trade_date),
    CONSTRAINT fk_ai_portfolio_backtest_position_run FOREIGN KEY (backtest_run_id) REFERENCES ai_portfolio_backtest_run (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_pipeline_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    data_batch_id BIGINT NULL,
    strategy_release_id BIGINT NULL,
    model_version_id BIGINT NULL,
    trade_date DATE NOT NULL,
    pipeline_type VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    input_fingerprint VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    execution_owner VARCHAR(64) NULL,
    lease_until DATETIME(3) NULL,
    current_step VARCHAR(64) NULL,
    processed_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_pipeline_run_idempotency (user_id, idempotency_key),
    KEY idx_ai_pipeline_run_trade_status (user_id, trade_date, pipeline_type, status),
    KEY idx_ai_pipeline_run_status (status, started_at),
    KEY idx_ai_pipeline_run_lease (status, lease_until),
    KEY idx_ai_pipeline_run_batch (data_batch_id),
    KEY idx_ai_pipeline_run_release (strategy_release_id, trade_date),
    CONSTRAINT fk_ai_pipeline_run_batch FOREIGN KEY (data_batch_id) REFERENCES ai_data_batch (id),
    CONSTRAINT fk_ai_pipeline_run_release FOREIGN KEY (strategy_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_pipeline_run_model FOREIGN KEY (model_version_id) REFERENCES ai_model_version (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_pipeline_step (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    pipeline_run_id BIGINT NOT NULL,
    step_key VARCHAR(64) NOT NULL,
    step_order INT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    retry_count INT NOT NULL DEFAULT 0,
    input_count INT NOT NULL DEFAULT 0,
    output_count INT NOT NULL DEFAULT 0,
    checkpoint_json MEDIUMTEXT NULL,
    output_fingerprint VARCHAR(128) NULL,
    error_message TEXT NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_pipeline_step_run_key (pipeline_run_id, step_key),
    KEY idx_ai_pipeline_step_status (pipeline_run_id, status, step_order),
    CONSTRAINT fk_ai_pipeline_step_run FOREIGN KEY (pipeline_run_id) REFERENCES ai_pipeline_run (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_shadow_evaluation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    pipeline_run_id BIGINT NULL,
    training_dataset_id BIGINT NULL,
    champion_release_id BIGINT NOT NULL,
    challenger_release_id BIGINT NOT NULL,
    champion_model_version_id BIGINT NULL,
    challenger_model_version_id BIGINT NULL,
    window_start_date DATE NOT NULL,
    window_end_date DATE NOT NULL,
    evaluation_version VARCHAR(64) NOT NULL,
    input_fingerprint VARCHAR(128) NOT NULL,
    sample_count INT NOT NULL DEFAULT 0,
    eligible_sample_count INT NOT NULL DEFAULT 0,
    coverage_rate DECIMAL(10, 6) NOT NULL DEFAULT 0,
    action_agreement_rate DECIMAL(10, 6) NULL,
    champion_calibration_error DECIMAL(12, 6) NULL,
    challenger_calibration_error DECIMAL(12, 6) NULL,
    champion_excess_return DECIMAL(12, 6) NULL,
    challenger_excess_return DECIMAL(12, 6) NULL,
    champion_max_drawdown DECIMAL(12, 6) NULL,
    challenger_max_drawdown DECIMAL(12, 6) NULL,
    feature_drift_score DECIMAL(12, 6) NULL,
    metrics_json MEDIUMTEXT NOT NULL,
    decision_status VARCHAR(32) NOT NULL DEFAULT 'OBSERVING',
    evaluated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_shadow_evaluation_window (user_id, champion_release_id, challenger_release_id, window_start_date, window_end_date, evaluation_version),
    KEY idx_ai_shadow_evaluation_candidate (user_id, decision_status, evaluated_at),
    KEY idx_ai_shadow_evaluation_challenger (challenger_release_id, window_end_date),
    CONSTRAINT chk_ai_shadow_evaluation_window CHECK (window_start_date <= window_end_date),
    CONSTRAINT chk_ai_shadow_evaluation_releases CHECK (champion_release_id <> challenger_release_id),
    CONSTRAINT fk_ai_shadow_evaluation_pipeline FOREIGN KEY (pipeline_run_id) REFERENCES ai_pipeline_run (id),
    CONSTRAINT fk_ai_shadow_evaluation_dataset FOREIGN KEY (training_dataset_id) REFERENCES ai_training_dataset (id),
    CONSTRAINT fk_ai_shadow_evaluation_champion FOREIGN KEY (champion_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_shadow_evaluation_challenger FOREIGN KEY (challenger_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_shadow_evaluation_champion_model FOREIGN KEY (champion_model_version_id) REFERENCES ai_model_version (id),
    CONSTRAINT fk_ai_shadow_evaluation_challenger_model FOREIGN KEY (challenger_model_version_id) REFERENCES ai_model_version (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_shadow_evaluation_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    shadow_evaluation_id BIGINT NOT NULL,
    sample_id BIGINT NOT NULL,
    champion_prediction_id BIGINT NOT NULL,
    challenger_prediction_id BIGINT NOT NULL,
    label_id BIGINT NULL,
    horizon_days INT NOT NULL,
    action_agreement TINYINT NOT NULL,
    score_delta DECIMAL(12, 6) NULL,
    confidence_delta DECIMAL(12, 6) NULL,
    challenger_excess_return DECIMAL(12, 6) NULL,
    evaluation_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_LABEL',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_shadow_evaluation_item_sample (shadow_evaluation_id, sample_id, horizon_days),
    KEY idx_ai_shadow_eval_item_challenger (challenger_prediction_id, evaluation_status),
    KEY idx_ai_shadow_eval_item_label (label_id),
    CONSTRAINT chk_ai_shadow_evaluation_predictions CHECK (champion_prediction_id <> challenger_prediction_id),
    CONSTRAINT fk_ai_shadow_eval_item_evaluation FOREIGN KEY (shadow_evaluation_id) REFERENCES ai_shadow_evaluation (id),
    CONSTRAINT fk_ai_shadow_eval_item_sample FOREIGN KEY (sample_id) REFERENCES ai_sample_v2 (id),
    CONSTRAINT fk_ai_shadow_eval_item_champion FOREIGN KEY (champion_prediction_id) REFERENCES ai_prediction_v2 (id),
    CONSTRAINT fk_ai_shadow_eval_item_challenger FOREIGN KEY (challenger_prediction_id) REFERENCES ai_prediction_v2 (id),
    CONSTRAINT fk_ai_shadow_eval_item_label FOREIGN KEY (label_id) REFERENCES ai_label_v2 (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_drift_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    factor_performance_id BIGINT NULL,
    model_version_id BIGINT NULL,
    strategy_release_id BIGINT NULL,
    shadow_evaluation_id BIGINT NULL,
    event_fingerprint VARCHAR(128) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    subject_type VARCHAR(32) NOT NULL,
    subject_key VARCHAR(160) NOT NULL,
    detector_version VARCHAR(64) NOT NULL,
    window_start_date DATE NOT NULL,
    window_end_date DATE NOT NULL,
    metric_name VARCHAR(64) NOT NULL,
    baseline_value DECIMAL(20, 8) NULL,
    observed_value DECIMAL(20, 8) NULL,
    threshold_value DECIMAL(20, 8) NULL,
    severity VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    evidence_json MEDIUMTEXT NOT NULL,
    detected_at DATETIME(3) NOT NULL,
    acknowledged_at DATETIME(3) NULL,
    resolved_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_drift_event_fingerprint (user_id, event_fingerprint),
    KEY idx_ai_drift_event_open (user_id, status, severity, detected_at),
    KEY idx_ai_drift_event_subject (subject_type, subject_key, window_end_date),
    KEY idx_ai_drift_event_performance (factor_performance_id),
    CONSTRAINT chk_ai_drift_event_window CHECK (window_start_date <= window_end_date),
    CONSTRAINT fk_ai_drift_event_performance FOREIGN KEY (factor_performance_id) REFERENCES ai_factor_performance_v2 (id),
    CONSTRAINT fk_ai_drift_event_model FOREIGN KEY (model_version_id) REFERENCES ai_model_version (id),
    CONSTRAINT fk_ai_drift_event_release FOREIGN KEY (strategy_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_drift_event_shadow FOREIGN KEY (shadow_evaluation_id) REFERENCES ai_shadow_evaluation (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_strategy_governance_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    strategy_release_id BIGINT NOT NULL,
    previous_champion_release_id BIGINT NULL,
    walk_forward_run_id BIGINT NULL,
    backtest_run_id BIGINT NULL,
    shadow_evaluation_id BIGINT NULL,
    event_key VARCHAR(160) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    decision_status VARCHAR(32) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id BIGINT NULL,
    reason TEXT NOT NULL,
    threshold_snapshot_json MEDIUMTEXT NOT NULL,
    evidence_json MEDIUMTEXT NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_strategy_governance_event_key (user_id, event_key),
    KEY idx_ai_strategy_governance_release (strategy_release_id, occurred_at),
    KEY idx_ai_strategy_governance_decision (user_id, decision_status, occurred_at),
    CONSTRAINT fk_ai_strategy_governance_release FOREIGN KEY (strategy_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_strategy_governance_previous FOREIGN KEY (previous_champion_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_strategy_governance_walk_run FOREIGN KEY (walk_forward_run_id) REFERENCES ai_walk_forward_run (id),
    CONSTRAINT fk_ai_strategy_governance_backtest FOREIGN KEY (backtest_run_id) REFERENCES ai_portfolio_backtest_run (id),
    CONSTRAINT fk_ai_strategy_governance_shadow FOREIGN KEY (shadow_evaluation_id) REFERENCES ai_shadow_evaluation (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS ai_research_daily_report (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    report_version INT NOT NULL DEFAULT 1,
    pipeline_run_id BIGINT NULL,
    strategy_release_id BIGINT NULL,
    model_version_id BIGINT NULL,
    supersedes_report_id BIGINT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    is_current TINYINT NOT NULL DEFAULT 1,
    current_report_guard TINYINT GENERATED ALWAYS AS (CASE WHEN is_current = 1 THEN 1 ELSE NULL END) STORED,
    report_status VARCHAR(32) NOT NULL DEFAULT 'READY',
    title VARCHAR(160) NOT NULL,
    executive_summary TEXT NOT NULL,
    market_regime VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    recommendation_count INT NOT NULL DEFAULT 0,
    watch_count INT NOT NULL DEFAULT 0,
    avoid_count INT NOT NULL DEFAULT 0,
    holding_risk_count INT NOT NULL DEFAULT 0,
    freshness_status VARCHAR(32) NOT NULL DEFAULT 'UNAVAILABLE',
    data_quality_score DECIMAL(10, 4) NOT NULL DEFAULT 0,
    content_json MEDIUMTEXT NOT NULL,
    markdown_content MEDIUMTEXT NULL,
    generated_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uk_ai_daily_report_user_date_version (user_id, trade_date, report_version),
    UNIQUE KEY uk_ai_daily_report_idempotency (user_id, idempotency_key),
    UNIQUE KEY uk_ai_daily_report_current (user_id, trade_date, current_report_guard),
    KEY idx_ai_daily_report_current (user_id, is_current, trade_date),
    KEY idx_ai_daily_report_status (user_id, report_status, freshness_status),
    KEY idx_ai_daily_report_pipeline (pipeline_run_id),
    CONSTRAINT chk_ai_daily_report_current CHECK (is_current IN (0, 1)),
    CONSTRAINT fk_ai_daily_report_pipeline FOREIGN KEY (pipeline_run_id) REFERENCES ai_pipeline_run (id),
    CONSTRAINT fk_ai_daily_report_release FOREIGN KEY (strategy_release_id) REFERENCES ai_strategy_release (id),
    CONSTRAINT fk_ai_daily_report_model FOREIGN KEY (model_version_id) REFERENCES ai_model_version (id),
    CONSTRAINT fk_ai_daily_report_supersedes FOREIGN KEY (supersedes_report_id) REFERENCES ai_research_daily_report (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
