server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:maogou;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:data-local.sql

maogou:
  scheduler:
    enabled: false
